services:
  api:
    build:
      context: .               # <- the folder where THIS compose file lives
      dockerfile: ./Dockerfile # <- explicit path to Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
